maintainer        "Infochimps.org"
maintainer_email  "help@infochimps.org"
license           "Apache 2.0"
description       "A bunch of useful packages to include."
long_description  ""
version           "0.1"
